"""Add code intelligence tables

Revision ID: adda9e53e8db
Revises: 20261001
Create Date: 2026-10-02 11:35:19.783210
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "adda9e53e8db"
down_revision = "20261001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_readiness_reports_experiment_id"), table_name="readiness_reports")
    op.drop_index(op.f("ix_readiness_reports_id"), table_name="readiness_reports")
    op.drop_index(op.f("ix_readiness_reports_repository_id"), table_name="readiness_reports")
    op.drop_table("readiness_reports")
    op.drop_index(op.f("ix_readiness_items_id"), table_name="readiness_items")
    op.drop_index(op.f("ix_readiness_items_readiness_report_id"), table_name="readiness_items")
    op.drop_table("readiness_items")
    op.drop_index(op.f("ix_code_files_id"), table_name="code_files")
    op.drop_index(op.f("ix_code_files_repository_id"), table_name="code_files")
    op.drop_table("code_files")
    op.drop_index(op.f("ix_paper_audit_id"), table_name="paper_audit")
    op.drop_table("paper_audit")
    op.drop_index(
        op.f("ix_experiment_code_mappings_experiment_id"), table_name="experiment_code_mappings"
    )
    op.drop_index(op.f("ix_experiment_code_mappings_id"), table_name="experiment_code_mappings")
    op.drop_index(
        op.f("ix_experiment_code_mappings_repository_id"), table_name="experiment_code_mappings"
    )
    op.drop_table("experiment_code_mappings")
    op.drop_index(op.f("ix_code_evidence_code_file_id"), table_name="code_evidence")
    op.drop_index(op.f("ix_code_evidence_id"), table_name="code_evidence")
    op.drop_index(op.f("ix_code_evidence_repository_id"), table_name="code_evidence")
    op.drop_table("code_evidence")
    op.drop_index(op.f("ix_repositories_experiment_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_normalized_url"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_paper_id"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("paper_id", sa.INTEGER(), nullable=True),
        sa.Column("experiment_id", sa.INTEGER(), nullable=True),
        sa.Column("url", sa.VARCHAR(length=2048), nullable=False),
        sa.Column("normalized_url", sa.VARCHAR(length=2048), nullable=False),
        sa.Column("owner", sa.VARCHAR(length=128), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("branch", sa.VARCHAR(length=255), nullable=True),
        sa.Column("commit_sha", sa.VARCHAR(length=128), nullable=True),
        sa.Column(
            "analyzed_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("file_count", sa.INTEGER(), nullable=False),
        sa.Column("python_file_count", sa.INTEGER(), nullable=False),
        sa.Column("total_bytes", sa.INTEGER(), nullable=False),
        sa.Column("warnings", sqlite.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_repositories_paper_id"), "repositories", ["paper_id"], unique=False)
    op.create_index(
        op.f("ix_repositories_normalized_url"), "repositories", ["normalized_url"], unique=False
    )
    op.create_index(op.f("ix_repositories_id"), "repositories", ["id"], unique=False)
    op.create_index(
        op.f("ix_repositories_experiment_id"), "repositories", ["experiment_id"], unique=False
    )
    op.create_table(
        "code_evidence",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("repository_id", sa.INTEGER(), nullable=False),
        sa.Column("code_file_id", sa.INTEGER(), nullable=True),
        sa.Column("file_path", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("evidence_type", sa.VARCHAR(length=64), nullable=False),
        sa.Column("symbol", sa.VARCHAR(length=255), nullable=True),
        sa.Column("value", sqlite.JSON(), nullable=True),
        sa.Column("line_start", sa.INTEGER(), nullable=True),
        sa.Column("line_end", sa.INTEGER(), nullable=True),
        sa.Column("quote", sa.TEXT(), nullable=True),
        sa.Column("confidence", sa.FLOAT(), nullable=False),
        sa.Column("verified", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["code_file_id"],
            ["code_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_evidence_repository_id"), "code_evidence", ["repository_id"], unique=False
    )
    op.create_index(op.f("ix_code_evidence_id"), "code_evidence", ["id"], unique=False)
    op.create_index(
        op.f("ix_code_evidence_code_file_id"), "code_evidence", ["code_file_id"], unique=False
    )
    op.create_table(
        "experiment_code_mappings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("experiment_id", sa.INTEGER(), nullable=False),
        sa.Column("repository_id", sa.INTEGER(), nullable=False),
        sa.Column("paper_field", sa.VARCHAR(length=128), nullable=False),
        sa.Column("paper_value", sqlite.JSON(), nullable=True),
        sa.Column("code_field", sa.VARCHAR(length=128), nullable=True),
        sa.Column("code_value", sqlite.JSON(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("confidence", sa.FLOAT(), nullable=False),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("code_evidence_id", sa.INTEGER(), nullable=True),
        sa.Column("paper_evidence", sqlite.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["code_evidence_id"],
            ["code_evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_code_mappings_repository_id"),
        "experiment_code_mappings",
        ["repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_code_mappings_id"), "experiment_code_mappings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_experiment_code_mappings_experiment_id"),
        "experiment_code_mappings",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "paper_audit",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("paper_id", sa.INTEGER(), nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=128), nullable=False),
        sa.Column("event_details", sqlite.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_paper_audit_id"), "paper_audit", ["id"], unique=False)
    op.create_table(
        "code_files",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("repository_id", sa.INTEGER(), nullable=False),
        sa.Column("path", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("file_type", sa.VARCHAR(length=32), nullable=True),
        sa.Column("role", sa.VARCHAR(length=64), nullable=False),
        sa.Column("confidence", sa.FLOAT(), nullable=False),
        sa.Column("size_bytes", sa.INTEGER(), nullable=True),
        sa.Column("evidence", sqlite.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_files_repository_id"), "code_files", ["repository_id"], unique=False
    )
    op.create_index(op.f("ix_code_files_id"), "code_files", ["id"], unique=False)
    op.create_table(
        "readiness_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("readiness_report_id", sa.INTEGER(), nullable=False),
        sa.Column("category", sa.VARCHAR(length=64), nullable=False),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("weight", sa.FLOAT(), nullable=False),
        sa.Column("score", sa.FLOAT(), nullable=False),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("evidence", sqlite.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["readiness_report_id"],
            ["readiness_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_readiness_items_readiness_report_id"),
        "readiness_items",
        ["readiness_report_id"],
        unique=False,
    )
    op.create_index(op.f("ix_readiness_items_id"), "readiness_items", ["id"], unique=False)
    op.create_table(
        "readiness_reports",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("experiment_id", sa.INTEGER(), nullable=False),
        sa.Column("repository_id", sa.INTEGER(), nullable=False),
        sa.Column("overall_score", sa.FLOAT(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column(
            "generated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_readiness_reports_repository_id"),
        "readiness_reports",
        ["repository_id"],
        unique=False,
    )
    op.create_index(op.f("ix_readiness_reports_id"), "readiness_reports", ["id"], unique=False)
    op.create_index(
        op.f("ix_readiness_reports_experiment_id"),
        "readiness_reports",
        ["experiment_id"],
        unique=False,
    )
    # ### end Alembic commands ###
